# configs/experiment_01.yaml
#experiment
#name: experiment_01

## Data loader
augment: true
batch_size: 100

## Training details
test_interval: 5
trainfunc: aamsoftmax
patience: 15

## Optimizer
optimizer: adam
lr: 0.001

## Loss functions
margin: 0.2
scale: 30
nPerSpeaker: 1
nClasses: 5991

## Training and test data
train_list: ${SL_SPV_DATA_ROOT}/train_list.txt
test_list: ${SL_SPV_DATA_ROOT}/list_test_all_formated_cleaned.txt
train_path : ${SL_SPV_DATA_ROOT}/rearranged_voxceleb2
test_path : ${SL_SPV_DATA_ROOT}/rearranged_voxceleb1
musan_path: ${SL_SPV_DATA_ROOT}/musan
rir_path: ${SL_SPV_DATA_ROOT}/RIRS_NOISES/simulated_rirs

## Model definition
n_mels: 64
model: ResNetSE34L

## Load and save paths
save_path: exps/my_first_custom_model
