#!/usr/bin/env python3
"""Build the full report package: HTML + Markdown + PDF + individual figures.

Layout produced:

    data/datasets_reports/
    ├── README.md                       index
    ├── <dataset>/
    │   ├── <dataset>.html              same content as the published artifact
    │   ├── <dataset>.md
    │   ├── <dataset>.pdf
    │   └── figures/NN_<key>.png|.svg   every figure, individually
    └── comparison/
        ├── comparison.{html,md,pdf}
        └── figures/

All three formats come from one block list per report (tools/qc_report_model.py),
so they cannot disagree.

Usage:
    python tools/build_report_package.py
"""
from __future__ import annotations

import json
import os
import shutil
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import qc_figures as F
import qc_report_model as M
from build_qc_reports import (CSS, ORDER, TITLES, collect, speaker_count,
                              verdict_for)

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
DATA = os.path.join(REPO, "data")
QC = os.path.join(DATA, "_qc")
OUT = os.path.join(DATA, "datasets_reports")

FOOTER = ("Generated by tools/build_report_package.py from the Layer 0-6 outputs "
          "under data/_qc/. Method: research_logs/"
          "2026-08-10-dataset-quality-assessment-methods-and-plan.md. Results: "
          "research_logs/2026-08-10-dataset-qc-results.md. Embeddings: "
          "SpeechBrain ECAPA-TDNN (VoxCeleb), 192-d, cosine.")


def jload(p, d=None):
    return json.load(open(p, encoding="utf-8")) if os.path.isfile(p) else d


BIAS = jload(os.path.join(QC, "bias_transfer", "bias.json"), {})
SHIFT = jload(os.path.join(QC, "bias_transfer", "shift.json"), {})
CALIB = jload(os.path.join(QC, "calibration", "calibration.json"), {})


# --------------------------------------------------------------------------- #
def dataset_blocks(d, figs):
    """Return the block list for one dataset report."""
    name = d["name"]
    title, langs, lic = TITLES.get(name, (name, "", ""))
    q, a, s = d["qc"], d["audit"], d["sig"]
    L0, L2, L4 = (q.get("L0_integrity", {}), q.get("L2_distribution", {}),
                  q.get("L4_protocol", {}))
    spk, vcls, vbullets = verdict_for(d)
    tot_u = sum(v["utterances"] for v in L2.values())
    tot_h = sum(v["hours"] for v in L2.values())
    B = []

    mdes = [(l, v["MDE_pct"]["rho_0.7_typical_paired"])
            for l, v in (d["power"] or {}).items()]
    best = min(mdes, key=lambda x: x[1]) if mdes else None
    dpr = a.get("separability_dprime")
    B.append(("kpis", [
        ("Speakers", f"{spk:,}", "after identity corrections", ""),
        ("Utterances", f"{tot_u:,}", f"{tot_h:.1f} h", ""),
        ("Separability d'", f"{dpr:.2f}" if dpr else "—", "within vs between",
         "good" if (dpr or 0) > 3.5 else "warn"),
        ("Best MDE", f"{best[1]:.2f} pp" if best else "—",
         best[0].replace("test_list", "tl") if best else "",
         ("good" if best[1] <= .2 else "warn" if best[1] <= .5 else "bad")
         if best else ""),
    ]))
    B.append(("callout", "bad" if vcls == "bad" else ("warn" if vcls == "warn" else ""),
              "Verdict.", " ".join(vbullets)))

    # ---- L0
    B.append(("h2", "L0", "Integrity and inventory"))
    B.append(("dek", "Is the data physically what the metadata claims?"))
    md_, au = L0.get("metadata_derived", {}), L0.get("audio_sampled", {})
    bw = au.get("effective_bandwidth_hz", {})
    rows = [
        ["Source sample rates",
         ", ".join(f"{k} Hz x{v:,}" for k, v in md_.get("source_sample_rates", {}).items()),
         "uniform" if md_.get("source_rate_uniform") else "MIXED"],
        ["Output format", "16 kHz / mono / PCM_16", "standardised"],
        ["Decode failures", f"{au.get('decode_failures', 0)} of {au.get('sampled', 0):,}",
         "clean" if not au.get("decode_failures") else "FAIL"],
        ["Near-silent files", str(au.get("near_silent_files", 0)),
         "clean" if not au.get("near_silent_files") else "check"],
        ["Clipped > 0.1 %", str(au.get("clipped_files_over_0.1pct", 0)),
         "clean" if not au.get("clipped_files_over_0.1pct") else "check"],
        ["Cross-speaker duplicates", str(au.get("cross_speaker_duplicate_pairs", 0)),
         "none" if not au.get("cross_speaker_duplicate_pairs") else "FAIL"],
    ]
    if bw:
        rows.append(["Effective bandwidth (median)",
                     f"{bw.get('median', 0):,.0f} Hz of {bw.get('nyquist', 8000):,.0f} Hz",
                     f"{bw.get('median_over_nyquist', 0)*100:.0f} % of band"])
    B.append(("table", ["Check", "Value", "Status"], rows))
    B.append(("p", "The bandwidth check exists to catch audio upsampled from a "
                   "narrowband source: it would still carry a 16 kHz header while "
                   "its energy stops near 4 kHz."))
    B.append(("endsection",))

    # ---- L2
    B.append(("h2", "L2", "Distribution and coverage"))
    for lang, v in L2.items():
        h, u = v["duration_histogram"], v["utts_per_speaker"]
        B.append(("h3", f"Language: {lang}"))
        su = v["short_utterance_fraction"]["under_2s"]
        B.append(("kpis", [
            ("Speakers", f"{v['speakers']:,}", "", ""),
            ("Median utts/spk", f"{u['median']:.0f}", f"Gini {u['gini']:.3f}", ""),
            ("Median duration", f"{v['duration_s']['median']:.1f} s",
             f"p05 {v['duration_s']['p05']:.1f} / p95 {v['duration_s']['p95']:.1f}", ""),
            ("Under 2 s", f"{su*100:.1f} %", "SV degrades below 2 s",
             "good" if su < .05 else "warn"),
        ]))
        F.RETURN_FIG = True
        figs_key = figs.add_figure(f"duration_{lang}",
                                   F.duration_hist(h["bin_edges_s"], h["counts"],
                                                   f"Duration - {lang}"))
        F.RETURN_FIG = False
        B.append(("fig", figs_key,
                  "Dashed line marks 2 s, below which verification accuracy falls "
                  "away sharply."))
        sess = v["sessions_per_speaker"]
        B.append(("p", f"Sessions per speaker: median {sess['median']:.0f}, "
                       f"{sess['speakers_multi_session']:,} speakers with more than "
                       f"one ({sess['frac_multi_session']*100:.0f} %)."))
    B.append(("endsection",))

    # ---- L1
    if s:
        B.append(("h2", "L1", "Signal quality and the channel confound"))
        dist, conf = s.get("distributions", {}), s.get("speaker_confound_anova", {})
        kp = []
        for k, lab, unit in [("snr_db", "SNR", " dB"),
                             ("speech_ratio", "Speech ratio", ""),
                             ("squim_pesq", "SQUIM PESQ", ""),
                             ("squim_stoi", "SQUIM STOI", "")]:
            if k in dist:
                kp.append((lab, f"{dist[k]['median']:.2f}{unit}",
                           f"p05 {dist[k]['p05']:.2f} / p95 {dist[k]['p95']:.2f}", ""))
        if kp:
            B.append(("kpis", kp))
        B.append(("math", "One-way ANOVA across speakers",
                  r"F=\frac{MS_{between}}{MS_{within}}"
                  r"=\frac{\sum_g n_g(\bar{x}_g-\bar{x})^2/(k-1)}"
                  r"{\sum_g\sum_{i\in g}(x_i-\bar{x}_g)^2/(N-k)}"
                  r"\qquad \eta^2=\frac{SS_{between}}{SS_{total}}"))
        if conf:
            F.RETURN_FIG = True
            k2 = figs.add_figure("anova_confound", F.anova_bars(conf))
            F.RETURN_FIG = False
            B.append(("fig", k2,
                      "How much of each metric's variance is explained by speaker "
                      "identity. Above 0.5 the metric is effectively a partial "
                      "speaker label, and a model can score channel instead of voice."))
        e2 = conf.get("snr_db", {}).get("eta_squared")
        if e2 is not None and e2 > .5:
            B.append(("callout", "warn", "Channel is partly identity here.",
                      f"Speaker explains {e2*100:.0f} % of the variance in SNR, so "
                      f"some of what looks like speaker discrimination is "
                      f"recording-condition discrimination. It inflates "
                      f"within-corpus results and does not transfer."))
        B.append(("endsection",))

    # ---- L3
    B.append(("h2", "L3", "Label reliability"))
    if a:
        c = a.get("clustering_vs_labels", {})
        fk, th = c.get("fixed_k", {}), c.get("threshold_0.5", {})
        B.append(("kpis", [
            ("d' separability", f"{a['separability_dprime']:.2f}", "within vs between", ""),
            ("NMI vs labels", f"{fk.get('NMI', 0):.3f}", f"ARI {fk.get('ARI', 0):.3f}",
             "good" if fk.get("NMI", 0) > .95 else "warn"),
            ("Purity", f"{fk.get('purity', 0):.3f}",
             f"clusters/speakers {th.get('clusters_over_speakers', 0):.2f}", ""),
            ("Silhouette", f"{a['silhouette']['mean']:.3f}", "cosine, 192-d", ""),
        ]))
        B.append(("math", "Leave-one-out own-speaker centroid",
                  r"c_S^{(-i)}=\frac{1}{n_S-1}\sum_{j\in S,\,j\neq i}e_j"
                  r"\qquad score(i)=\frac{\langle e_i,\,c_S^{(-i)}\rangle}"
                  r"{\|c_S^{(-i)}\|}"))
        B.append(("math", "Separability index",
                  r"d'=\frac{\mu_{within}-\mu_{between}}"
                  r"{\sqrt{(\sigma^2_{within}+\sigma^2_{between})/2}}"))
        if d["dists"] is not None:
            z = d["dists"]
            F.RETURN_FIG = True
            k3 = figs.add_figure("cosine_distributions",
                                 F.cosine_distributions(z["within"], z["between"],
                                                        a["separability_dprime"]))
            k4 = figs.add_figure("loo_centroid",
                                 F.loo_hist(z["loo"],
                                            a["loo_centroid_cosine"]["frac_below_0.3"]))
            F.RETURN_FIG = False
            B.append(("fig", k3,
                      "The two distributions a verification system must separate. "
                      "Overlap is the irreducible error floor for this embedding."))
            B.append(("fig", k4,
                      "Utterances far from their own speaker's centroid are mislabel "
                      f"candidates. The left tail is the listening shortlist "
                      f"({len(d['short'])} files in data/_qc/label_audit/)."))
        B.append(("math", "Clustering agreement",
                  r"NMI=\frac{2\,I(U;V)}{H(U)+H(V)}\qquad"
                  r"purity=\frac{1}{N}\sum_k \max_j |u_k\cap v_j|"))
        cs = th.get("clusters_over_speakers")
        if cs is not None and (cs > 1.4 or cs < .75):
            direction = ("more clusters than labelled speakers, which suggests "
                         "speakers split by channel or session" if cs > 1 else
                         "fewer clusters than labelled speakers, which suggests "
                         "labels that are really the same person")
            B.append(("callout", "warn",
                      f"Clustering finds {cs:.2f}x as many groups as labels.",
                      f"That is {direction}. Threshold-based cluster counts move "
                      f"with the threshold, so read this as a direction to "
                      f"investigate, not a measurement."))
    B.append(("endsection",))

    # ---- projections
    if d["proj"] is not None:
        p = d["proj"]
        short = {r["path"] for r in d["short"]}
        flag = np.array([x in short for x in p["path"]])
        B.append(("h2", "2D", "t-SNE and UMAP"))
        B.append(("dek", "The same speaker subsample under both projections. "
                         "Structure that appears in only one is an artefact of that "
                         "algorithm; trust what survives both."))
        F.RETURN_FIG = True
        kt = figs.add_figure("tsne", F.scatter_projection(
            p["tsne"], p["spk"], "t-SNE", "cosine / perplexity 30", flag))
        B.append(("fig", kt, "t-SNE preserves local neighbourhoods; distances "
                             "between separated blobs carry no meaning. Red rings "
                             "mark the mislabel shortlist."))
        if len(p["umap"]):
            ku = figs.add_figure("umap", F.scatter_projection(
                p["umap"], p["spk"], "UMAP", "cosine / n_neighbors 15", flag))
            B.append(("fig", ku, "UMAP on the same points, retaining more global "
                                 "structure."))
        F.RETURN_FIG = False
        B.append(("p", "Explore interactively: `streamlit run tools/tsne_explorer.py` "
                       "and `tools/umap_explorer.py`."))
        B.append(("endsection",))

    # ---- bespoke: the session effect, measurable only where sessions are real
    se_path = os.path.join(QC, f"{name.replace('_sinhala','').replace('_tamil','')}"
                               f"_session_effect.json")
    se = jload(os.path.join(QC, "slceleb2026_session_effect.json")) \
        if name == "slceleb2026_sinhala" else None
    if se:
        B.append(("h2", "SE", "The same-recording confound, measured"))
        B.append(("dek", "This corpus is the only one here with genuine sessions, "
                         "so it is the only one that can measure the confound the "
                         "whole methodology is built around."))
        B.append(("table", ["Pair type", "Mean cosine"],
                  [["Same speaker, same session", f"{se['within_session_mean']:.3f}"],
                   ["Same speaker, different session",
                    f"{se['cross_session_mean']:.3f}"],
                   ["Different speakers", f"{se['between_speaker_mean']:.3f}"]]))
        B.append(("kpis", [
            ("Session penalty", f"{se['session_penalty']:.3f}",
             "cosine lost by changing recording", "warn"),
            ("d' same-session", f"{se['dprime_same_session']:.2f}",
             "what a same-recording protocol reports", "bad"),
            ("d' cross-session", f"{se['dprime_cross_session']:.2f}",
             "the honest number", "good"),
            ("Inflation", f"{se['dprime_same_session']/se['dprime_cross_session']:.0%}",
             "of apparent separability", "bad"),
        ]))
        B.append(("callout", "bad",
                  "Scoring targets from the same recording inflates separability "
                  f"by {se['dprime_same_session']/se['dprime_cross_session']-1:.0%}.",
                  "d' is "
                  f"{se['dprime_same_session']:.2f} when same-session pairs are "
                  f"allowed and {se['dprime_cross_session']:.2f} when they are "
                  "not, on identical speakers and one embedding. Every other "
                  "corpus in this collection uses one-session-per-utterance, "
                  "which is the same-sitting condition -- so their reported "
                  "separability, and their EERs, carry an optimism of roughly "
                  "this size. That is the concrete reason this corpus's 11 % EER "
                  "and SLR127's 1.07 % are not comparable numbers."))
        B.append(("endsection",))

    # ---- L4
    if L4:
        B.append(("h2", "L4", "Trial-list audit"))
        rows = []
        for k, v in L4.items():
            if not isinstance(v, dict) or "trials" not in v:
                continue
            sg = v.get("same_gender_impostor_fraction")
            ov = v.get("train_test_speaker_overlap")
            rows.append([k, f"{v['trials']:,}", f"{v['targets']:,}",
                         str(v.get("self_pairs", 0)),
                         str(v["same_speaker_session_targets"]),
                         str(v["impostors_sharing_a_speaker"]),
                         "n/a" if sg is None else f"{sg:.2f}",
                         "—" if ov is None else str(ov)])
        B.append(("table", ["List", "Trials", "Targets", "Self-pairs",
                            "Same-sess", "Bad imp.", "Gender", "Overlap"], rows))
        B.append(("p", "*Self-pairs* counts trials that pair a file with itself "
                       "(must be 0). *Same-session* counts target pairs drawn from "
                       "one recording (must be 0). *Bad impostors* counts impostor "
                       "pairs that actually share a speaker (must be 0). "
                       "*Same-gender* is the fraction of impostor pairs matched on "
                       "gender, where gender is known. *Overlap* is the number of "
                       "speakers in both the train list and the trial list."))
        worst = max((v.get("self_pairs", 0) for v in L4.values()
                     if isinstance(v, dict) and "trials" in v), default=0)
        if worst:
            B.append(("callout", "bad",
                      f"{worst:,} target trials pair a file with itself.",
                      "These are AI4Bharat's official lists, unmodified, so this is "
                      "a defect in the published protocol rather than in our "
                      "preparation. A self-pair scores cosine 1.0 by construction "
                      "and is always accepted, so it cannot contribute a miss — the "
                      "reported EER is biased slightly low. The lists are left "
                      "untouched on purpose: altering them would break "
                      "comparability with every published IndicSUPERB number, which "
                      "is the only reason to use this corpus. Quote the EER with "
                      "this caveat attached."))
        B.append(("endsection",))

    # ---- L5 + calibration
    if d["power"]:
        B.append(("h2", "L5", "Difficulty, calibration and statistical power"))
        B.append(("math", "Speaker-clustered bootstrap",
                  r"S_b\sim\ sample(\mathcal{S},n,\text{replace})"
                  r"\quad EER_b=EER(\bigcup_{s\in S_b}T_s)\quad SE=sd(EER_b)"))
        B.append(("math", "Minimum detectable effect",
                  r"MDE=(z_{1-\alpha/2}+z_{1-\beta})\,SE\sqrt{2(1-\rho)}"
                  r"\;=\;2.802\,SE\sqrt{2(1-\rho)}"))
        cal = CALIB.get(name, {})
        rows = []
        for k, v in d["power"].items():
            cv = cal.get(k, {})
            rows.append([k, f"{v['EER_avg']:.2f}",
                         f"{v['bootstrap']['CI95_pct'][0]:.2f}-{v['bootstrap']['CI95_pct'][1]:.2f}",
                         f"{v.get('minDCF_p0.01', 0):.3f}",
                         f"{cv.get('Cllr', float('nan')):.4f}" if cv else "—",
                         f"{cv.get('minCllr', float('nan')):.4f}" if cv else "—",
                         str(v["distinct_speakers"]),
                         f"{v['MDE_pct']['rho_0.7_typical_paired']:.2f}"])
        B.append(("table", ["List", "EER %", "95 % CI", "minDCF", "Cllr", "minCllr",
                            "Speakers", "MDE pp"], rows))
        B.append(("math", "Cost of log-likelihood-ratio",
                  r"C_{llr}=\frac{1}{2}\left[\frac{1}{|T|}\sum_{i\in T}"
                  r"\log_2(1+e^{-llr_i})+\frac{1}{|N|}\sum_{j\in N}"
                  r"\log_2(1+e^{llr_j})\right]"))
        first = list(d["power"].values())[0]
        F.RETURN_FIG = True
        kb = figs.add_figure("bootstrap_ci", F.bootstrap_ci(
            first["bootstrap"]["mean"], first["bootstrap"]["CI95_pct"],
            first["MDE_pct"]["rho_0.7_typical_paired"],
            first["MDE_pct"]["rho_0.0_conservative"], first["EER_avg"]))
        F.RETURN_FIG = False
        B.append(("fig", kb,
                  "Point estimate with its speaker-clustered 95 % interval. The "
                  "shaded bands are the minimum effect this corpus could resolve; "
                  "an ablation delta smaller than the band is not measurable here, "
                  "however many trials are run."))
        B.append(("endsection",))

    # ---- L6
    bias = BIAS.get(name, {})
    B.append(("h2", "L6", "Subgroup fairness"))
    if bias.get("status"):
        B.append(("callout", "warn", "Not measurable for this corpus.",
                  bias["status"] + " Any claim about subgroup parity here would be "
                  "unfounded."))
    elif bias:
        B.append(("math", "Fairness discrepancy rate",
                  r"FDR=1-\left[\alpha\max_{g,h}|FMR_g-FMR_h|"
                  r"+(1-\alpha)\max_{g,h}|FNMR_g-FNMR_h|\right]"))
        rows = []
        for lst, v in bias.items():
            for g, r in v["subgroups"].items():
                rows.append([f"{lst} / {g}", f"{r['FNMR']:.4f}", f"{r['FMR']:.4f}",
                             f"{r['targets']:,}", f"{r['impostors']:,}",
                             f"{v['FDR']:.4f}"])
        B.append(("table", ["List / subgroup", "FNMR", "FMR", "Targets",
                            "Impostors", "FDR"], rows))
        B.append(("p", "Rates are at the single pooled EER threshold, which is what "
                       "a deployed system actually uses. FDR = 1 is perfect parity."))
    B.append(("endsection",))

    meta = {
        "title": f"{title} — QC report",
        "eyebrow": "SL_SPV / dataset quality report",
        "h1": title,
        "sub": "Layers 0-6 of the quality assessment, run end to end.",
        "byline": [name, langs, lic, "2026-08-10"],
        "running_head": f"{title} — QC report",
        "footer": FOOTER,
    }
    return meta, B


# --------------------------------------------------------------------------- #
def comparison_blocks(ds, figs):
    names = [d["name"] for d in ds]
    spk, hours, utts, dpr, nmi, sil, mde, eer, eta = ([] for _ in range(9))
    for d in ds:
        L2 = d["qc"].get("L2_distribution", {})
        spk.append(speaker_count(d))
        hours.append(sum(v["hours"] for v in L2.values()))
        utts.append(sum(v["utterances"] for v in L2.values()))
        a = d["audit"]
        dpr.append(a.get("separability_dprime", 0))
        nmi.append(a.get("clustering_vs_labels", {}).get("fixed_k", {}).get("NMI", 0))
        sil.append(a.get("silhouette", {}).get("mean", 0))
        eta.append(d["sig"].get("speaker_confound_anova", {})
                   .get("snr_db", {}).get("eta_squared", 0))
        bm, be = None, None
        for l, v in (d["power"] or {}).items():
            m = v["MDE_pct"]["rho_0.7_typical_paired"]
            if bm is None or m < bm:
                bm, be = m, v["EER_avg"]
        mde.append(bm if bm is not None else float("nan"))
        eer.append(be if be is not None else float("nan"))

    B = []
    valid = [m for m in mde if m == m]
    B.append(("kpis", [
        ("Corpora measured", "6", "338k utterances", ""),
        ("Total speakers", f"{sum(spk):,}", "after identity corrections", ""),
        ("Best MDE", f"{min(valid):.2f} pp" if valid else "—",
         "smallest resolvable effect", "warn"),
        ("Channel probe", f"{SHIFT.get('channel_probe', {}).get('accuracy', 0)*100:.1f} %",
         f"chance {SHIFT.get('channel_probe', {}).get('chance', 0)*100:.0f} %", "bad"),
    ]))

    B.append(("h2", "01", "The master table"))
    rows = []
    for i, d in enumerate(ds):
        t = TITLES.get(d["name"], (d["name"], "", ""))
        rows.append([d["name"], t[1], f"{spk[i]:,}", f"{utts[i]:,}",
                     f"{hours[i]:.1f}", f"{dpr[i]:.2f}", f"{nmi[i]:.3f}",
                     f"{sil[i]:.3f}", f"{eta[i]:.2f}", f"{eer[i]:.2f}",
                     f"{mde[i]:.2f}"])
    B.append(("table", ["Corpus", "Lang", "Speakers", "Utts", "Hours", "d'", "NMI",
                        "Silhouette", "eta2(SNR)", "EER %", "MDE pp"], rows))
    B.append(("endsection",))

    B.append(("h2", "02", "Can any corpus resolve an ablation effect?"))
    B.append(("dek", "The question the whole assessment exists to answer."))
    F.RETURN_FIG = True
    k = figs.add_figure("mde", F.mde_chart(names, eer, mde))
    F.RETURN_FIG = False
    B.append(("fig", k, "Minimum detectable effect from a speaker-clustered "
                        "bootstrap at rho=0.7. Anything right of the red line "
                        "cannot support a defensible ranking of feature variants."))
    B.append(("math", "Minimum detectable effect",
              r"MDE=(z_{1-\alpha/2}+z_{1-\beta})\,SE\sqrt{2(1-\rho)}"
              r",\qquad \alpha=0.05,\ 1-\beta=0.8"))
    bi = int(np.nanargmin(mde))
    bm = mde[bi]
    if bm <= .2:
        B.append(("callout", "", f"{names[bi]} is adequately powered",
                  f"at MDE {bm:.2f} pp. The ablation can proceed as designed."))
    elif bm <= .5:
        B.append(("callout", "warn",
                  f"{names[bi]} is the only corpus close to usable power —",
                  f"MDE {bm:.2f} pp, just above the 0.2 pp target and well inside "
                  f"the 0.5 pp limit. Large feature effects are rankable; a wide "
                  f"grid of small ones is not. Narrow the ablation to fewer, bolder "
                  f"conditions on {names[bi]}, and treat every other corpus as "
                  f"confirmatory."))
    else:
        B.append(("callout", "bad", "No corpus reaches even the 0.5 pp limit.",
                  "That is the 'more speakers before more experiments' case."))
    B.append(("callout", "", "Trials do not buy power; speakers do.",
              f"Kathbath supplies 50,000 official trials and lands at MDE "
              f"{max(valid):.2f} pp on 20 speakers, while {names[bi]} reaches "
              f"{bm:.2f} pp from 12,000 trials over {spk[bi]}. Sampling more pairs "
              f"from the same voices re-uses information already in the corpus."))
    B.append(("endsection",))

    B.append(("h2", "03", "Scale and shape"))
    F.RETURN_FIG = True
    k1 = figs.add_figure("scale", F.scatter_speakers_hours(names, spk, hours, mde))
    dur = []
    for d in ds:
        L2 = d["qc"].get("L2_distribution", {})
        if L2:
            v = list(L2.values())[0]["duration_histogram"]
            dur.append((d["name"], v["bin_edges_s"], v["counts"]))
    k2 = figs.add_figure("durations", F.duration_overlay(dur)) if dur else None
    F.RETURN_FIG = False
    B.append(("fig", k1, "Speakers against hours, both log. Marker area encodes "
                         "1/MDE (clipped to a legible range), so bigger means more "
                         "statistical power — and the vertical spread shows how "
                         "little hours buy compared with speakers."))
    if k2:
        B.append(("fig", k2, "Duration profiles. Mass below 2 s costs EER for "
                             "reasons unrelated to the speakers."))
    B.append(("endsection",))

    B.append(("h2", "04", "Label quality and separability"))
    F.RETURN_FIG = True
    k3 = figs.add_figure("dprime", F.compare_bars(names, dpr, "d'",
                                                  "Speaker separability",
                                                  thresholds=(4.0, 3.0)))
    k4 = figs.add_figure("nmi", F.compare_bars(names, nmi, "NMI",
                                                "Clustering vs given labels",
                                                thresholds=(.95, .90), fmt="{:.3f}"))
    F.RETURN_FIG = False
    B.append(("fig", k3, "d' between within- and between-speaker cosine "
                         "distributions."))
    B.append(("fig", k4, "Agreement between agglomerative clustering and the "
                         "distributed speaker labels."))
    B.append(("math", "Separability and agreement",
              r"d'=\frac{\mu_w-\mu_b}{\sqrt{(\sigma_w^2+\sigma_b^2)/2}}"
              r"\qquad NMI=\frac{2I(U;V)}{H(U)+H(V)}"))
    B.append(("endsection",))

    B.append(("h2", "05", "Is channel acting as identity?"))
    F.RETURN_FIG = True
    k5 = figs.add_figure("eta_snr", F.compare_bars(
        names, eta, "eta^2 of SNR across speakers", "Channel/speaker confound",
        thresholds=(.25, .5), higher_is_better=False, fmt="{:.2f}"))
    F.RETURN_FIG = False
    B.append(("fig", k5, "Fraction of the variance in per-utterance SNR explained "
                         "by speaker identity."))
    cp = SHIFT.get("channel_probe", {})
    if cp:
        B.append(("callout", "bad",
                  f"Corpus-of-origin is {cp['accuracy']*100:.1f} % linearly "
                  f"decodable from the speaker embedding",
                  f"(chance {cp['chance']*100:.0f} %). The embedding space encodes "
                  f"recording channel as strongly as it encodes anything "
                  f"corpus-independent, so cross-corpus comparisons are partly "
                  f"comparisons of microphones. This is the single strongest "
                  f"argument against quoting one corpus's absolute EER as a "
                  f"performance claim."))
    if SHIFT.get("frechet"):
        rows = [[k, f"{v:.3f}", f"{SHIFT['centroid_cosine'].get(k, 0):.3f}"]
                for k, v in SHIFT["frechet"].items()]
        B.append(("table", ["Corpus pair", "Frechet distance", "Centroid cosine"],
                  rows))
        B.append(("math", "Frechet distance between embedding distributions",
                  r"d^2=\|\mu_A-\mu_B\|^2+tr\left(\Sigma_A+\Sigma_B"
                  r"-2(\Sigma_A\Sigma_B)^{1/2}\right)"))
    B.append(("endsection",))

    tsne_items, umap_items = [], []
    for d in ds:
        if d["proj"] is not None:
            p = d["proj"]
            tsne_items.append((d["name"], p["tsne"], p["spk"]))
            if len(p["umap"]):
                umap_items.append((d["name"], p["umap"], p["spk"]))
    if tsne_items:
        B.append(("h2", "06", "Embedding space, side by side"))
        B.append(("dek", "Same protocol for every corpus: 14 speakers with at least "
                         "8 utterances, cosine metric, identical seed."))
        F.RETURN_FIG = True
        kt = figs.add_figure("grid_tsne", F.grid_projections(tsne_items, "t-SNE"))
        B.append(("fig", kt, "t-SNE. Tight, separated colour groups mean clean "
                             "labels and an easy corpus."))
        if umap_items:
            ku = figs.add_figure("grid_umap", F.grid_projections(umap_items, "UMAP"))
            B.append(("fig", ku, "UMAP on the same points. Structure appearing in "
                                 "both views is real."))
        F.RETURN_FIG = False
        B.append(("endsection",))

    meta = {
        "title": "Cross-dataset comparison — SL_SPV QC",
        "eyebrow": "SL_SPV / cross-dataset comparison",
        "h1": "Five Sinhala / Tamil corpora, measured side by side",
        "sub": "Layers 0-6 of the quality assessment, run end to end on every built "
               "corpus. One decision comes out of it: whether the feature ablation "
               "is worth running yet.",
        "byline": ["2026-08-10", "ECAPA-TDNN / cosine",
                   "speaker-clustered bootstrap B=1000"],
        "running_head": "Cross-dataset comparison — SL_SPV QC",
        "footer": FOOTER,
    }
    return meta, B


# --------------------------------------------------------------------------- #
def write_report(name, meta, blocks, figs, out_dir):
    html = M.render_html(meta, blocks, figs, CSS)
    with open(os.path.join(out_dir, f"{name}.html"), "w", encoding="utf-8") as fh:
        fh.write(html)
    md = M.render_md(meta, blocks, figs)
    with open(os.path.join(out_dir, f"{name}.md"), "w", encoding="utf-8") as fh:
        fh.write(md)
    M.render_pdf(meta, blocks, figs, os.path.join(out_dir, f"{name}.pdf"))
    n_png = len([f for f in os.listdir(figs.dir) if f.endswith(".png")])
    n_svg = len([f for f in os.listdir(figs.dir) if f.endswith(".svg")])
    print(f"[pkg] {name}: html+md+pdf, {n_png} png / {n_svg} svg figures")


def main():
    os.makedirs(OUT, exist_ok=True)
    ds = []
    for n in ORDER:
        if os.path.isdir(os.path.join(DATA, n)):
            d = collect(n)
            if d["qc"]:
                ds.append(d)

    index = ["# Dataset quality reports", "",
             "Layers 0-6 of the quality assessment, one folder per corpus. Each "
             "folder holds the same report as HTML, Markdown and PDF, plus every "
             "figure as an individual PNG and SVG under `figures/`.", "",
             "| Report | HTML | Markdown | PDF | Figures |", "|---|---|---|---|---|"]

    for d in ds:
        out_dir = os.path.join(OUT, d["name"])
        os.makedirs(out_dir, exist_ok=True)
        figs = M.Figures(out_dir)
        meta, blocks = dataset_blocks(d, figs)
        write_report(d["name"], meta, blocks, figs, out_dir)
        nf = len([f for f in os.listdir(figs.dir) if f.endswith(".png")])
        index.append(f"| {d['name']} | [html]({d['name']}/{d['name']}.html) | "
                     f"[md]({d['name']}/{d['name']}.md) | "
                     f"[pdf]({d['name']}/{d['name']}.pdf) | {nf} |")

    cdir = os.path.join(OUT, "comparison")
    os.makedirs(cdir, exist_ok=True)
    cfigs = M.Figures(cdir)
    cmeta, cblocks = comparison_blocks(ds, cfigs)
    write_report("comparison", cmeta, cblocks, cfigs, cdir)
    nf = len([f for f in os.listdir(cfigs.dir) if f.endswith(".png")])
    index.append(f"| **comparison** | [html](comparison/comparison.html) | "
                 f"[md](comparison/comparison.md) | "
                 f"[pdf](comparison/comparison.pdf) | {nf} |")

    index += ["", "Sources: `data/_qc/` (raw layer outputs). Method: "
                  "`research_logs/2026-08-10-dataset-quality-assessment-methods-and-plan.md`. "
                  "Results narrative: `research_logs/2026-08-10-dataset-qc-results.md`.", ""]
    with open(os.path.join(OUT, "README.md"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(index))
    print(f"[pkg] index -> {os.path.join(OUT, 'README.md')}")


if __name__ == "__main__":
    main()
